apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-speech-recognition
  labels:
    app: triton-speech-recognition
spec:
  selector:
    matchLabels:
      app: triton-speech-recognition
  template:
    metadata:
      labels:
        app: triton-speech-recognition
    spec:
      imagePullSecrets:
        - name: ngc-secret
      containers:
        - name: triton-frontend
          image: "{{ .Values.frontEndImage.repository }}:{{ .Values.frontEndImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontEndImage.pullPolicy }}
          ports:
            - name: jupyter
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          args:
            - jupyter
            - lab
            - --ip=0.0.0.0
            - --no-browser
            - --allow-root
            - --port=8888
            - --ServerApp.token=''
            - --ServerApp.password=''
            - --ServerApp.allow_origin='*'
            - --ServerApp.base_url=/
          volumeMounts:
            - name: triton-storage
              mountPath: /Kaldi/data
        - name: triton-backend
          image: "{{ .Values.backEndImage.repository }}:{{ .Values.frontEndImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backEndImage.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: triton-storage
              mountPath: /data
      initContainers:
        - name: prepare-data
          image: "{{ .Values.backEndImage.repository }}:{{ .Values.backEndImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backEndImage.pullPolicy }}
          command:
            - /workspace/scripts/docker/prepare_data.sh
          volumeMounts:
            - name: triton-storage
              mountPath: /data
      subdomain: default-subdomain
      volumes:
        - name: dshm
          emptyDir: {}
        - name: triton-storage
          emptyDir: {}