apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-speech-recognition
  labels:
    app: triton-speech-recognition
spec:
  selector:
    matchLabels:
      app: triton-speech-recognition
  template:
    metadata:
      labels:
        app: triton-speech-recognition
    spec:
      affinity: {{- toYaml .Values.frontendAffinity | nindent 12 }}
      imagePullSecrets:
        - name: ngc-secret
      subdomain: default-subdomain
      containers:
        - name: triton-speech-recognition-frontend
          image: "{{ .Values.frontEndImage.repository }}:{{ .Values.frontEndImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontEndImage.pullPolicy }}
          ports:
            - name: jupyter
              containerPort: 8888
              protocol: TCP
          args:
            - jupyter
            - lab
            - --ip=0.0.0.0
            - --no-browser
            - --allow-root
            - --port=8888
            - --ServerApp.token=''
            - --ServerApp.password=''
            - --ServerApp.allow_origin='*'
            - --ServerApp.base_url=/
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: triton-frontend-storage
              mountPath: /Kaldi/data
              readOnly: true
          resources: {{- toYaml .Values.resources | nindent 12 }}
      nodeName: {{ .Values.frontendNodeName }}
      initContainers:
        - name: init-data
          image: "{{ .Values.backEndImage.repository }}:{{ .Values.backEndImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backEndImage.pullPolicy }}
          command:
            - /workspace/scripts/prepare_data.sh
          volumeMounts:
            - name: triton-frontend-storage
              mountPath: /data
      volumes:
        - name: dshm
          emptyDir: {}
        - name: triton-frontend-storage
          persistentVolumeClaim:
            claimName: triton-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-speech-recognition-backend
  labels:
    app: triton-speech-recognition
spec:
  selector:
    matchLabels:
      app: triton-speech-recognition
  template:
    metadata:
      labels:
        app: triton-speech-recognition
    spec:
      affinity: {{- toYaml .Values.backendAffinity | nindent 12 }}
      imagePullSecrets:
        - name: ngc-secret
      subdomain: default-subdomain
      containers:
        - name: triton-backend
          image: "{{ .Values.backEndImage.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backEndImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: grpc
              containerPort: 8001
              protocol: TCP
            - name: metrics
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: triton-backend-storage
              mountPath: /data
          resources: {{- toYaml .Values.resources | nindent 12 }}
      nodeName: {{ .Values.backendNodeName }}
      initContainers:
        - name: init-server-config
          image: "{{ .Values.backEndImage.repository }}:{{ .Values.backEndImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backEndImage.pullPolicy }}
          command: ['sh', '-c', 'echo Waiting for frontend app to start... && sleep 60']
      volumes:
        - name: dshm
          emptyDir: {}
        - name: triton-backend-storage
          persistentVolumeClaim:
            claimName: triton-storage
