apiVersion: v1
kind: PersistentVolume
metadata:
  name: triton-pv
  labels:
    app: triton-speech-recognition
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: triton-sc
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}