kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: triton-storage
  labels:
    app: triton-speech-recognition
spec:
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi