apiVersion: v1
kind: Service
metadata:
  name: triton-frontend
  labels:
    app: triton-speech-recognition
spec:
  ports:
    - name: jupyter
      nodePort: {{ .Values.serviceFrontend.nodePort }}
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: triton-speech-recognition-frontend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: triton-backend
  labels:
    app: triton-speech-recognition
spec:
  ports:
    - name: http
      nodePort: {{ .Values.serviceBackend.nodePortHTTP }}
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: grpc
      nodePort: {{ .Values.serviceBackend.nodePortGRPC }}
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: metrics
      nodePort: {{ .Values.serviceBackend.nodePortMetrics }}
      port: 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: triton-speech-recognition-backend
  type: NodePort