services:
  kaldi-speechrecognition-server:
    image: nvcr.io/nvidian/sae/k8s-triton-speech-recognition-server
    build:
      context: SpeechRecognition
      dockerfile: Dockerfile

  kaldi-speechrecognition:
    image: nvcr.io/nvidian/sae/k8s-triton-speech-recognition
    build:
      context: SpeechRecognition
      dockerfile: Dockerfile.notebook