apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-speech-recognition
  labels:
    app: triton-speech-recognition
spec:
  selector:
    matchLabels:
      app: triton-speech-recognition
  template:
    metadata:
      labels:
        app: triton-speech-recognition
    spec:
      containers:
        - name: triton-frontend
          image: nvcr.io/nvidian/sae/k8s-triton-speech-recognition:0.1.0
          ports:
            - containerPort: 8888
              name: jupyter
              protocol: TCP
          args:
            - jupyter
            - lab
            - --ip=0.0.0.0
            - --no-browser
            - --allow-root
            - --port=8888
            - --ServerApp.token=''
            - --ServerApp.password=''
            - --ServerApp.allow_origin='*'
            - --ServerApp.base_url=/
          volumeMounts:
            - name: triton-storage
              mountPath: /Kaldi/data
        - name: triton-backend
          image: nvcr.io/nvidian/sae/k8s-triton-speech-recognition-server:0.1.0
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: triton-storage
              mountPath: /data
      initContainers:
        - name: prepare-data
          image: nvcr.io/nvidian/sae/k8s-triton-speech-recognition-server:0.1.0
          command:
            - /workspace/scripts/prepare_data.sh
          volumeMounts:
            - name: triton-storage
              mountPath: /data
      subdomain: default-subdomain
      volumes:
        - name: dshm
          emptyDir: {}
        - name: triton-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: triton-frontend
spec:
  ports:
    - name: jupyter
      nodePort: 30888
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: triton-speech-recognition
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: triton-backend
spec:
  ports:
    - name: "triton-http"
      port: 8000
      targetPort: 8000
    - name: "triton-grpc"
      port: 8001
      targetPort: 8001
    - name: "triton-metrics"
      port: 8002
      targetPort: 8002
  selector:
    app: triton-speech-recognition